name: Autocloser
on: [issues]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Autoclose issues that did not follow issue template
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login} this issue was automatically closed because it did not follow the [Bug Report](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/new?assignees=&labels=bug&template=bug_report.yml) or [Feature Request](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/new?assignees=JurajNyiri&labels=enhancement&template=feature_request.md&title=Feature+Request%3A) template."
          issue-pattern: ".*Camera has all attributes filled out in developer tools.*|.*Is your feature request related to a problem.*"
  autoclose-cloud-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue description for invalid string
        id: check_body
        run: |
          if [[ "${{ github.event.issue.body }}" == *"cloud password"* ]]; then
            echo "contains_invalid_string=true" >> $GITHUB_ENV
          else
            echo "contains_invalid_string=false" >> $GITHUB_ENV
          fi
      - name: Close Issue - comment
        if: env.contains_invalid_string == 'true'
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            This issue was automatically closed because it is a duplicate.
            
            The issue you are searching for:
            - Is pinned under issues
            - Has a section in main readme file with big title right at the top
            - Has 3 red exclamations marks in the title
            - Contains a workaround both for accounts still working and the ones affected.
            
            And a warning was sent a month ago as an update via HACS.

            You can find it at https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551.

            Please do not post me too comments or any other comment that does not provide any value to the discussion as everyone monitoring it gets notified. If the comments with no value continue maintainer will be forced to lock the issue to contributors only.
          labels: |
            Duplicate
